[package]
name = "roget"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
itertools = "0.10.3"
clap = { version = "4", features = ["derive"] }
once_cell = "1"